//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sigurd.Terminal.Properties {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Sigurd.Terminal.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string DirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("DirectoryDoesNotExist", resourceCulture);
            }
        }
        
        internal static string OptionExpectsOneArgument {
            get {
                return ResourceManager.GetString("OptionExpectsOneArgument", resourceCulture);
            }
        }
        
        internal static string FileDoesNotExist {
            get {
                return ResourceManager.GetString("FileDoesNotExist", resourceCulture);
            }
        }
        
        internal static string FileOrDirectoryDoesNotExist {
            get {
                return ResourceManager.GetString("FileOrDirectoryDoesNotExist", resourceCulture);
            }
        }
        
        internal static string InvalidCharactersInPath {
            get {
                return ResourceManager.GetString("InvalidCharactersInPath", resourceCulture);
            }
        }
        
        internal static string CommandRequiredArgumentMissing {
            get {
                return ResourceManager.GetString("CommandRequiredArgumentMissing", resourceCulture);
            }
        }
        
        internal static string OptionRequiredArgumentMissing {
            get {
                return ResourceManager.GetString("OptionRequiredArgumentMissing", resourceCulture);
            }
        }
        
        internal static string RequiredCommandWasNotProvided {
            get {
                return ResourceManager.GetString("RequiredCommandWasNotProvided", resourceCulture);
            }
        }
        
        internal static string UnrecognizedArgument {
            get {
                return ResourceManager.GetString("UnrecognizedArgument", resourceCulture);
            }
        }
        
        internal static string UnrecognizedCommandOrArgument {
            get {
                return ResourceManager.GetString("UnrecognizedCommandOrArgument", resourceCulture);
            }
        }
        
        internal static string ResponseFileNotFound {
            get {
                return ResourceManager.GetString("ResponseFileNotFound", resourceCulture);
            }
        }
        
        internal static string ErrorReadingResponseFile {
            get {
                return ResourceManager.GetString("ErrorReadingResponseFile", resourceCulture);
            }
        }
        
        internal static string HelpOptionDescription {
            get {
                return ResourceManager.GetString("HelpOptionDescription", resourceCulture);
            }
        }
        
        internal static string InvalidCharactersInFileName {
            get {
                return ResourceManager.GetString("InvalidCharactersInFileName", resourceCulture);
            }
        }
        
        internal static string HelpUsageAdditionalArguments {
            get {
                return ResourceManager.GetString("HelpUsageAdditionalArguments", resourceCulture);
            }
        }
        
        internal static string HelpUsageCommand {
            get {
                return ResourceManager.GetString("HelpUsageCommand", resourceCulture);
            }
        }
        
        internal static string HelpUsageOptions {
            get {
                return ResourceManager.GetString("HelpUsageOptions", resourceCulture);
            }
        }
        
        internal static string HelpUsageTitle {
            get {
                return ResourceManager.GetString("HelpUsageTitle", resourceCulture);
            }
        }
        
        internal static string HelpDescriptionTitle {
            get {
                return ResourceManager.GetString("HelpDescriptionTitle", resourceCulture);
            }
        }
        
        internal static string HelpArgumentDefaultValueLabel {
            get {
                return ResourceManager.GetString("HelpArgumentDefaultValueLabel", resourceCulture);
            }
        }
        
        internal static string HelpArgumentsTitle {
            get {
                return ResourceManager.GetString("HelpArgumentsTitle", resourceCulture);
            }
        }
        
        internal static string HelpOptionsRequiredLabel {
            get {
                return ResourceManager.GetString("HelpOptionsRequiredLabel", resourceCulture);
            }
        }
        
        internal static string HelpOptionsTitle {
            get {
                return ResourceManager.GetString("HelpOptionsTitle", resourceCulture);
            }
        }
        
        internal static string HelpAdditionalArgumentsDescription {
            get {
                return ResourceManager.GetString("HelpAdditionalArgumentsDescription", resourceCulture);
            }
        }
        
        internal static string HelpAdditionalArgumentsTitle {
            get {
                return ResourceManager.GetString("HelpAdditionalArgumentsTitle", resourceCulture);
            }
        }
        
        internal static string HelpCommandsTitle {
            get {
                return ResourceManager.GetString("HelpCommandsTitle", resourceCulture);
            }
        }
        
        internal static string ExceptionHandlerHeader {
            get {
                return ResourceManager.GetString("ExceptionHandlerHeader", resourceCulture);
            }
        }
        
        internal static string SuggestionsTokenNotMatched {
            get {
                return ResourceManager.GetString("SuggestionsTokenNotMatched", resourceCulture);
            }
        }
        
        internal static string VersionOptionCannotBeCombinedWithOtherArguments {
            get {
                return ResourceManager.GetString("VersionOptionCannotBeCombinedWithOtherArguments", resourceCulture);
            }
        }
        
        internal static string VersionOptionDescription {
            get {
                return ResourceManager.GetString("VersionOptionDescription", resourceCulture);
            }
        }
        
        internal static string ArgumentConversionCannotParse {
            get {
                return ResourceManager.GetString("ArgumentConversionCannotParse", resourceCulture);
            }
        }
        
        internal static string ArgumentConversionCannotParseForCommand {
            get {
                return ResourceManager.GetString("ArgumentConversionCannotParseForCommand", resourceCulture);
            }
        }
        
        internal static string ArgumentConversionCannotParseForOption {
            get {
                return ResourceManager.GetString("ArgumentConversionCannotParseForOption", resourceCulture);
            }
        }
        
        internal static string RequiredOptionWasNotProvided {
            get {
                return ResourceManager.GetString("RequiredOptionWasNotProvided", resourceCulture);
            }
        }
        
        internal static string ArgumentConversionCannotParseForCommand_Completions {
            get {
                return ResourceManager.GetString("ArgumentConversionCannotParseForCommand_Completions", resourceCulture);
            }
        }
        
        internal static string ArgumentConversionCannotParseForOption_Completions {
            get {
                return ResourceManager.GetString("ArgumentConversionCannotParseForOption_Completions", resourceCulture);
            }
        }
    }
}
